### ISSUE TITLE
Files should be saved in module context instead of course context

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-moodle-plugin#112]
From discussion at https://tracker.moodle.org/browse/MDL-55758

> Is course context a valid place to save the files in the first place? Should the plugin be updated to save them in the module context instead?
## 

> Well, it means all your mod_hvp activities in a course are sharing the same area, so if you were to perform a backup of one of them it would backup all the files belonging to all of them.

So, instead of this:

``` php
$context = \context_course::instance($COURSE->id); // <-- Wrong way
$options = array(
    'contextid' => $context->id,
    'component' => 'mod_hvp',
    'filearea' => 'content',
    'itemid' => $id,
    'filepath' => '/',
);
```

The plugin should be doing something like this:

``` php
$context = \context_module::instance($cmid); // <-- Correct way
$options = array(
    'contextid' => $context->id,
    'component' => 'mod_hvp',
    'filearea' => 'content',
    'itemid' => $id,
    'filepath' => '/',
);
```

Besides this fix, an upgrade script is required to update existing `mdl_files` table entries to use the correct context.

**Comment by juho-jaakkola** [comment]
More hands-on example of the problem:

Lets say that I have a Moodle course with 100 H5P activities. I want to make a backup of one of them. Because the files related to the activity have been saved in the course context instead of the module context, the backup will in fact include all the files from all the 100 activities.

**Comment by icc** [comment]
Ah, that makes sense and I guess it would be even easier to see if I did some debugging and looking into the contexts. I just naturally assumed that the module context was a level above the course context and not the other way around, silly me. 

Have you tried changing it and seeing if it works as expected?
I guess changing the context of the files shouldn't be too big of an issue.

Very well spotted!

**Comment by juho-jaakkola** [comment]
I looked into the database structure to figure out the needed changes, but didn't yet have time to do any actual changes or testing.

**Comment by icc** [comment]
Ok, so I made changes that give all the content files the course module context instead of just course. I also added an upgrade script that updates the context for existing files.

The exports filearea should also be moved to the CM context(mostly for access control reasons), but I didn't want to do too much at once.

Be aware that tmpfiles(_editor_ filearea) and exports probably shouldn't be part of the backups, I don't know if there's some way to just ignore these?

Please help test that nothing has broken :-) 
(and remember to do a submodule update after pulling)

**Comment by juho-jaakkola** [comment]
I got an error when I tried to update existin H5P content:
```
Trying to get property of non-object in /var/www/moodle/31/mod/hvp/classes/file_storage.php on line 560
```

**Comment by juho-jaakkola** [comment]
It works when `file_storage::getFile()` is being called with the `content` filearea. The error happens when filearea is `editor`:

```
filearea: string(6) "editor"
itemid: int(0)
file: string(43) "https://www.youtube.com/watch?v=r3nqoR3RlJY"
cm: bool(false)
```

**Comment by icc** [comment]
The issue should be fixed by the last commit.

However, I'm a bit puzzled to find the YouTube URL there… perhaps [h5peditor.class.php#L248](https://github.com/h5p/h5p-editor-php-library/blob/improved-file-handling/h5peditor.class.php#L248) should have had a URL check or something.

**Comment by juho-jaakkola** [comment]
I'm unable to upload new packages:

```
line 6802 of /lib/moodlelib.php: coding_exception thrown
line 331 of /mod/hvp/classes/framework.php: call to get_string()
line 1322 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->t()
line 134 of /mod/hvp/lib.php: call to H5PStorage->savePackage()
line 86 of /mod/hvp/lib.php: call to hvp_save_content()
line 121 of /course/modlib.php: call to hvp_add_instance()
line 275 of /course/modedit.php: call to add_moduleinfo()

Output buffer:
Notice: Trying to get property of non-object in /var/www/moodle/31/mod/hvp/classes/file_storage.php on line 98
Notice: Undefined index: Invalid course module ID in /var/www/moodle/31/mod/hvp/classes/framework.php on line 331
```

**Comment by icc** [comment]
Of course, the 'instance to CM-id' function won't work until after the new content is saved. Fixed it by just using the whole content object/array while saving.

Should be working now :-)

**Comment by icc** [comment]
Did you manage to take a look at the last fix? If so, I think we can just close this issue.

**Comment by juho-jaakkola** [comment]
Petri did and he said there's still problems. I haven't confirmed this yet.

**Comment by juho-jaakkola** [comment]
Still getting errors.

## Trying to upload a new package:
```
Stack trace:
line 6802 of /lib/moodlelib.php: coding_exception thrown
line 331 of /mod/hvp/classes/framework.php: call to get_string()
line 1322 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->t()
line 134 of /mod/hvp/lib.php: call to H5PStorage->savePackage()
line 86 of /mod/hvp/lib.php: call to hvp_save_content()
line 121 of /course/modlib.php: call to hvp_add_instance()
line 275 of /course/modedit.php: call to add_moduleinfo()
```
This error seems to be caused by the string `Invalid course module ID` so the problem is in fact with creation of the course module, not translations.

## Trying to download existing package:
```
Sorry, the requested file could not be found

Stack trace:
line 495 of /lib/setuplib.php: moodle_exception thrown
line 1803 of /lib/filelib.php: call to print_error()
line 4620 of /lib/filelib.php: call to send_file_not_found()
line 37 of /pluginfile.php: call to file_pluginfile()
```

**Comment by icc** [comment]
Are you sure that you pulled and updated the submodules? The call to `mod_hvp\framework->t()` should have been removed.

**Comment by icc** [comment]
But indeed, the download is broken :-( I'll look into it…

**Comment by icc** [comment]
Fixed, checked for the wrong context.

**Comment by juho-jaakkola** [comment]
Downloading works now with the latest fix.

I will test the database upgrade script once more, and then close the issue, if it is successful.

**Comment by juho-jaakkola** [comment]
Status report:
 - Content created with `1.0-rc.2` survived the upgrade to latest [master](e169b639a73d01ed3c2cda93163b3b8940e64938)
 - Creation of new contents works
 - The Download feature works

The upgrade script did however cause the following error in one environment:

```
Debug info: Duplicate entry '58ba0c87e6bc0a1dda40ab0c0537affaa6d677bd'
for key 'file_pat_uix'

UPDATE files SET
contextid = 41635,
pathnamehash = '58ba0c87e6bc0a1dda40ab0c0537affaa6d677bd'
WHERE pathnamehash = '0a4a82ea3fb22747988f0ebb99e0f622fb8caa4c'
[array (
)]
```

I would assume this has something to do with a situation, where author has uploaded two identical H5P packages to a course. The media is identical and the context is identical (the course context). So somehow the upgrade script fails to save the database entry. Not sure, though. This is just speculation.

**Comment by icc** [comment]
Thank you for the update!

Yes, the pathnamehash is essentially a combination of contextid, component(mod_hvp), filearea(content), itemid(id in hvp table), filepath(e.g. /images/) and filename(h5p.png) used to easily find the file.

I find it strange that there should be two of the same file… I don't quite see how that could have happened. It would be interesting to know if they had the same contenthash as well.

**Comment by atrnoble** [comment]
Currently having similar issues when trying to add an image to an interactive video. The context being applied at this level is incorrect and means that as as soon as the image is added, you end up with a missing resource in the console.

**Comment by icc** [comment]
This should be fixed and released now, so I'm closing this issue.
